### ISSUE TITLE
Android build with version 2.0.7 fails on Java 6

### ISSUE THREAD

**Issue by tverilytt** [silkimen/cordova-plugin-advanced-http#200]
Hi!
First of all, thanks for great plugin, it works great in background fetch, where Angular $http requests just hanged...

When updating to newest version, 2.0.7, the cordova build for Android fails. Cordova build uses Java 6, seems version 2.0.7 requires Java 7...

Anyone else run into this?
I use quite a few other plugins, and not sure to bump to Java 7...

Cheers
-jo

:compileDebugJavaWithJavac/Users/jo/dev/git/ionic/luftkvalitet/platforms/android/src/com/silkimen/cordovahttp/CordovaHttpBase.java:141: error: strings in switch are not supported in -source 1.6
    switch (this.serializer) {
           ^
  (use -source 7 or higher to enable strings in switch)
/Users/jo/dev/git/ionic/luftkvalitet/platforms/android/src/com/silkimen/cordovahttp/CordovaHttpBase.java:159: error: strings in switch are not supported in -source 1.6
    switch (this.serializer) {
           ^
  (use -source 7 or higher to enable strings in switch)
/Users/jo/dev/git/ionic/luftkvalitet/platforms/android/src/com/silkimen/cordovahttp/CordovaHttpPlugin.java:67: error: strings in switch are not supported in -source 1.6
    switch (action) {
           ^
  (use -source 7 or higher to enable strings in switch)
/Users/jo/dev/git/ionic/luftkvalitet/platforms/android/src/com/silkimen/cordovahttp/CordovaHttpPlugin.java:156: error: strings in switch are not supported in -source 1.6
      switch (args.getString(0)) {
             ^

**Comment by silkimen** [comment]
Hi Jo,

I'm using Java 7 on my dev machine, so I didn't realize this could be a problem. Thanks for reporting! I'll change all `switch` into `if ... else if ... else`. 😑

Cheers
Sefa

**Comment by tverilytt** [comment]
Hi! Cool, thanks! I actually have Java 8 on my dev machine. It seems Cordova sets they version some way. I tried to look for it, but main suggestions I found, was to modify build.gradle directly, and I want ot avoid that if not absolutely necessary...I am on Cordova 7.1 btw, time to upgrade I guess ;-)

**Comment by silkimen** [comment]
Ok, that's interesting. So, it seems to be depending on the cordova version. I'm using 8.1.2, btw. But I don't want to break compatibility with older versions, I'll fix this. Please, just stick to v2.0.6 meanwhile. Do you also experience other problems with Java target version 6 and v2.0.7?

**Comment by tverilytt** [comment]
Thanks a lot for that. I have not seen any other problems.
